#!/usr/bin/env bash
# shellcheck disable=SC2016

serena_usage() {
  cat >&2 <<'EOF'
Usage:
  agently serena status [--json]
  agently serena create-project [--apply] [--index]
  agently serena onboard --client <codex|claude-code> [--dry-run] [--profile <lite|review|edit>] [--output PATH]
  agently serena memories list
  agently serena memories check [--mark-reviewed]
  agently serena profile [get | set <lite|review|edit>]
  agently serena smoke [--output PATH] [--json]
  agently serena code-intel
  agently serena workflow-report
EOF
}

mcp_usage() {
  cat >&2 <<'EOF'
Usage:
  agently mcp status [--json]
  agently mcp add serena --client <codex|claude-code> [--profile P] [--apply] [--scope project|user]
  agently mcp remove serena --client <codex|claude-code> [--apply] [--scope project|user]
EOF
}

serena_templates_dir() {
  printf '%s/templates/serena\n' "$AGENTLY_SHARE"
}

serena_profile_normalize() {
  case "${1:-}" in
    lite|serena-lite) printf 'lite\n' ;;
    review|serena-review) printf 'review\n' ;;
    edit|serena-edit) printf 'edit\n' ;;
    *) return 1 ;;
  esac
}

serena_profile_settings() {
  local profile="$1"
  case "$profile" in
    lite)
      printf 'read_only=true\nmutation_capable=false\nsummary=Safe-ish semantic inspection.\n'
      ;;
    review)
      printf 'read_only=true\nmutation_capable=false\nsummary=Read-heavy review and audit mode.\n'
      ;;
    edit)
      printf 'read_only=false\nmutation_capable=true\nsummary=Mutation-capable semantic edit/refactor mode.\n'
      ;;
    *) return 1 ;;
  esac
}

serena_client_context() {
  case "$1" in
    codex) printf 'codex\n' ;;
    claude-code) printf 'claude-code\n' ;;
    *) return 1 ;;
  esac
}

serena_client_valid() {
  case "$1" in
    codex|claude-code) return 0 ;;
    *) return 1 ;;
  esac
}

serena_executable_safe() {
  local cmd="$1"
  [[ -n "$cmd" ]] || return 1
  case "$cmd" in
    *[[:space:]]*|*";"*|*"&"*|*"|"*|*"<"*|*">"*|*'`'*|*'$('*)
      return 1
      ;;
  esac
  return 0
}

serena_resolve_cmd() {
  if [[ -n "${AGENTLY_SERENA_CMD:-}" ]]; then
    agently_config_validate_env_override AGENTLY_SERENA_CMD
    serena_executable_safe "$AGENTLY_SERENA_CMD" || return 1
    if [[ "$AGENTLY_SERENA_CMD" == */* ]]; then
      [[ -x "$AGENTLY_SERENA_CMD" ]] || return 1
    else
      command -v "$AGENTLY_SERENA_CMD" >/dev/null 2>&1 || return 1
    fi
    printf '%s\n' "$AGENTLY_SERENA_CMD"
    return 0
  fi
  if has_cmd serena; then
    printf 'serena\n'
  elif has_cmd serena-mcp-server; then
    printf 'serena-mcp-server\n'
  else
    return 1
  fi
}

serena_command_for_snippet() {
  serena_resolve_cmd 2>/dev/null || printf 'serena\n'
}

serena_version_for_cmd() {
  local cmd="$1" version
  [[ -n "$cmd" ]] || return 1
  set +e
  version="$("$cmd" --version 2>/dev/null | sed -n '1p')"
  set -e
  [[ -n "$version" ]] || return 1
  printf '%s\n' "$version"
}

serena_generated_banner() {
  local command="$1"
  cat <<EOF
<!-- GENERATED by Agently -->
<!-- command: $command -->
<!-- agently_version: $(agently_version) -->
<!-- generated: $(now) -->

EOF
}

serena_reject_serena_output_path() {
  local root="$1" path="$2" cwd abs canonical_root canonical_path
  cwd="$(pwd -P)"
  case "$path" in
    /*) abs="$path" ;;
    *) abs="$cwd/$path" ;;
  esac
  canonical_root="$(realpath "$root" 2>/dev/null || printf '%s\n' "$root")"
  canonical_path="$(realpath -m "$abs" 2>/dev/null || printf '%s\n' "$abs")"
  case "$canonical_path" in
    "$canonical_root/.serena"|"$canonical_root/.serena"/*)
      die "refusing to write Agently output under .serena: $path"
      ;;
  esac
}

serena_render_template() {
  local src="$1" project="$2" root="$3" profile="$4" client="$5" command="$6"
  local serena_cmd read_only
  serena_cmd="$(serena_command_for_snippet)"
  case "$profile" in
    edit) read_only="false" ;;
    *) read_only="true" ;;
  esac
  render_file_to_stdout "$src" \
    "PROJECT=$project" \
    "REPO_ROOT=$root" \
    "CLIENT=$client" \
    "SERENA_PROFILE=$profile" \
    "SERENA_COMMAND=$serena_cmd" \
    "SERENA_READ_ONLY=$read_only" \
    "COMMAND=$command" \
    "AGENTLY_VERSION=$(agently_version)" \
    "DATE=$(today)" \
    "DATETIME=$(now)"
}

serena_render_generated_file() {
  local src="$1" dst="$2" mode="$3" project="$4" root="$5" profile="$6" client="$7" command="$8" dry_run="$9"
  local content label
  case "$dst" in
    "$root"/*) label="${dst#"$root"/}" ;;
    *) label="$dst" ;;
  esac
  content="$(serena_render_template "$src" "$project" "$root" "$profile" "$client" "$command")"
  case "$dst" in
    *.md) content="$(serena_generated_banner "$command")$content" ;;
  esac
  write_text_file "$dst" "$mode" "$content" 1 "$dry_run" "$label"
}

serena_render_pack() {
  local root="$1" project="$2" profile="$3" force="$4" dry_run="$5"
  local templates src rel dst content command
  templates="$(serena_templates_dir)"
  [[ -d "$templates" ]] || die "missing Serena templates at $templates"
  command="agently init --codex --serena"

  while IFS= read -r src; do
    rel="${src#"$templates/integrations/serena"/}"
    rel="${rel#/}"
    dst="$root/.agently/integrations/serena/$rel"
    content="$(serena_render_template "$src" "$project" "$root" "$profile" "codex" "$command")"
    write_text_file "$dst" 0644 "$content" "$force" "$dry_run" ".agently/integrations/serena/$rel"
  done < <(find "$templates/integrations/serena" -type f | sort)

  src="$templates/state.yml.tmpl"
  dst="$root/.agently/integrations/serena/state.yml"
  content="$(serena_render_template "$src" "$project" "$root" "$profile" "codex" "$command")"
  write_text_file "$dst" 0644 "$content" "$force" "$dry_run" ".agently/integrations/serena/state.yml"

  serena_render_generated "$root" "$project" "$profile" "$command" "$dry_run"
}

serena_render_generated() {
  local root="$1" project="$2" profile="$3" command="$4" dry_run="$5"
  local templates
  templates="$(serena_templates_dir)/generated/serena"
  serena_render_generated_file "$templates/onboard.codex.md.tmpl" \
    "$root/.agently/generated/serena/onboard.codex.md" 0644 "$project" "$root" "$profile" "codex" "$command" "$dry_run"
  serena_render_generated_file "$templates/onboard.claude-code.md.tmpl" \
    "$root/.agently/generated/serena/onboard.claude-code.md" 0644 "$project" "$root" "$profile" "claude-code" "$command" "$dry_run"
  serena_render_generated_file "$templates/codex.config.toml.example.tmpl" \
    "$root/.agently/generated/serena/codex.config.toml.example" 0644 "$project" "$root" "$profile" "codex" "$command" "$dry_run"
  serena_render_generated_file "$templates/claude-code.commands.sh.tmpl" \
    "$root/.agently/generated/serena/claude-code.commands.sh" 0755 "$project" "$root" "$profile" "claude-code" "$command" "$dry_run"
  serena_render_generated_file "$templates/project.yml.example.tmpl" \
    "$root/.agently/generated/serena/project.yml.example" 0644 "$project" "$root" "$profile" "codex" "$command" "$dry_run"
}

serena_config_set_enabled_profile() {
  local root="$1" enabled="$2" profile="$3" dry_run="$4"
  local normalized_enabled
  profile="$(serena_profile_normalize "$profile")" || die "invalid Serena profile: $profile"
  normalized_enabled="$(normalize_bool_value "$enabled")" || die "serena.enabled must be true or false"
  if [[ "$dry_run" -eq 1 ]]; then
    note "DRY update .agently/config.yml serena.enabled=$normalized_enabled serena.profile=$profile"
    return 0
  fi
  profile_set_config_key_for_root "$root" serena.enabled "$normalized_enabled"
  profile_set_config_key_for_root "$root" serena.profile "$profile"
}

serena_state_file_for() {
  local root="$1"
  printf '%s/.agently/integrations/serena/state.yml\n' "$root"
}

serena_state_get() {
  local root="$1" key="$2"
  config_get_top "$(serena_state_file_for "$root")" "$key"
}

serena_state_set() {
  local root="$1" key="$2" value="$3" file dir tmp
  file="$(serena_state_file_for "$root")"
  mkdir -p "$(dirname "$file")"
  if [[ ! -f "$file" ]]; then
    printf 'enabled: true\nprofile: lite\ncreated_at: %s\nupdated_at: %s\nmemories_reviewed: false\n' "$(now)" "$(now)" > "$file"
  fi
  dir="$(dirname "$file")"
  tmp="$(mktemp "$dir/.state.yml.tmp.XXXXXX")"
  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0 }
    $0 ~ "^" key ":[[:space:]]*" {
      print key ": " value
      done = 1
      next
    }
    { print }
    END {
      if (!done) {
        print key ": " value
      }
    }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
  if [[ "$key" != "updated_at" ]]; then
    serena_state_set "$root" updated_at "$(now)"
  fi
}

serena_codex_config_path() {
  printf '%s/config.toml\n' "${CODEX_HOME:-$HOME/.codex}"
}

serena_codex_mcp_block_count() {
  local file="$1"
  [[ -f "$file" ]] || { printf '0\n'; return 0; }
  grep -Ec '^\[mcp_servers\.serena\][[:space:]]*$' "$file" 2>/dev/null || printf '0\n'
}

serena_mcp_codex_state() {
  local file count
  file="$(serena_codex_config_path)"
  if [[ ! -f "$file" ]]; then
    printf 'not configured\n'
    return 0
  fi
  count="$(serena_codex_mcp_block_count "$file")"
  if [[ "$count" -gt 1 ]]; then
    printf 'duplicate\n'
  elif [[ "$count" -eq 1 ]]; then
    printf 'configured\n'
  else
    printf 'not configured\n'
  fi
}

serena_mcp_claude_state() {
  local root="$1" out
  if has_cmd claude; then
    set +e
    out="$(claude mcp list 2>/dev/null)"
    set -e
    if printf '%s\n' "$out" | grep -qi 'serena'; then
      printf 'configured\n'
    else
      printf 'not configured\n'
    fi
  elif [[ -n "$root" && -f "$root/.mcp.json" ]]; then
    if grep -qi 'serena' "$root/.mcp.json"; then
      printf 'configured\n'
    else
      printf 'not configured\n'
    fi
  else
    printf 'unknown\n'
  fi
}

serena_memory_snapshot_lines() {
  local root="$1" dir file rel size mtime
  dir="$root/.serena/memories"
  [[ -d "$dir" ]] || return 0
  while IFS= read -r file; do
    rel="$(rel_to_root "$root" "$file")"
    size="$(wc -c < "$file" 2>/dev/null || printf '0')"
    mtime="$(stat -c '%Y' "$file" 2>/dev/null || printf '0')"
    printf '%s|%s|%s\n' "$rel" "$size" "$mtime"
  done < <(find "$dir" -type f | sort)
}

serena_memory_count() {
  local root="$1"
  serena_memory_snapshot_lines "$root" | awk 'END { print NR + 0 }'
}

serena_memory_snapshot_file() {
  local root="$1"
  printf '%s/.agently/reports/serena-memories.snapshot\n' "$root"
}

serena_write_memory_snapshot() {
  local root="$1" file
  file="$(serena_memory_snapshot_file "$root")"
  mkdir -p "$(dirname "$file")"
  serena_memory_snapshot_lines "$root" > "$file"
  serena_state_set "$root" last_memory_snapshot_at "$(now)"
  serena_state_set "$root" last_memory_count "$(serena_memory_count "$root")"
  serena_state_set "$root" last_memory_snapshot_file ".agently/reports/serena-memories.snapshot"
  printf '%s\n' "$file"
}

serena_generated_stale_state() {
  local root="$1" file version stale=0
  version="$(agently_version)"
  for file in "$root/.agently/generated/serena/codex.config.toml.example" \
              "$root/.agently/generated/serena/claude-code.commands.sh" \
              "$root/.agently/generated/serena/project.yml.example" \
              "$root/.agently/generated/serena/onboard.codex.md" \
              "$root/.agently/generated/serena/onboard.claude-code.md"; do
    [[ -f "$file" ]] || continue
    if ! grep -Fq "$version" "$file"; then
      stale=1
    fi
  done
  [[ "$stale" -eq 1 ]] && printf 'yes' || printf 'no'
}

serena_collect_state() {
  local root="${1:-}" cmd=""
  SERENA_ROOT="$root"
  SERENA_ENABLED="false"
  SERENA_PROFILE="lite"
  SERENA_PROFILE_VALID="yes"
  SERENA_PACK_PRESENT="no"
  SERENA_CMD_STATUS="missing"
  SERENA_CMD=""
  SERENA_VERSION="unavailable"
  SERENA_TOKENS_VERIFIED="no"
  SERENA_PROJECT_YML="missing"
  SERENA_CACHE="missing"
  SERENA_MEMORIES="missing"
  SERENA_MEMORY_COUNT="0"
  SERENA_MEMORIES_REVIEWED="false"
  SERENA_CODEX_MCP="unknown"
  SERENA_CLAUDE_MCP="unknown"
  SERENA_GENERATED_STALE="no"
  SERENA_GENERATED_SCRIPT_EXEC="unknown"
  SERENA_WARNINGS=()
  SERENA_INFO=()

  if [[ -n "$root" && -f "$root/.agently/config.yml" ]]; then
    SERENA_ENABLED="$(profile_get_value serena.enabled)"
    SERENA_PROFILE="$(profile_get_value serena.profile)"
    if ! SERENA_PROFILE="$(serena_profile_normalize "$SERENA_PROFILE")"; then
      SERENA_PROFILE_VALID="no"
      SERENA_PROFILE="$(profile_get_value serena.profile)"
      SERENA_WARNINGS+=("serena.profile is invalid: $SERENA_PROFILE")
    fi
  fi

  if cmd="$(serena_resolve_cmd 2>/dev/null)"; then
    SERENA_CMD_STATUS="installed"
    SERENA_CMD="$cmd"
    SERENA_TOKENS_VERIFIED="yes"
    SERENA_VERSION="$(serena_version_for_cmd "$cmd" || printf 'unavailable')"
  elif has_cmd uvx; then
    SERENA_CMD_STATUS="uvx available; serena not installed"
    SERENA_INFO+=("uvx is available, but Agently did not execute a uvx Serena launch.")
  else
    SERENA_CMD_STATUS="missing"
  fi

  if [[ -n "$root" ]]; then
    [[ -d "$root/.agently/integrations/serena" ]] && SERENA_PACK_PRESENT="yes"
    [[ -f "$root/.serena/project.yml" ]] && SERENA_PROJECT_YML="found"
    if [[ -d "$root/.serena/cache" ]]; then
      if find "$root/.serena/cache" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
        SERENA_CACHE="present non-empty"
      else
        SERENA_CACHE="present empty"
      fi
    fi
    if [[ -d "$root/.serena/memories" ]]; then
      SERENA_MEMORY_COUNT="$(serena_memory_count "$root")"
      if [[ "$SERENA_MEMORY_COUNT" -gt 0 ]]; then
        SERENA_MEMORIES="present non-empty"
      else
        SERENA_MEMORIES="present empty"
      fi
    fi
    SERENA_MEMORIES_REVIEWED="$(serena_state_get "$root" memories_reviewed)"
    [[ -n "$SERENA_MEMORIES_REVIEWED" ]] || SERENA_MEMORIES_REVIEWED="false"
    SERENA_CODEX_MCP="$(serena_mcp_codex_state)"
    SERENA_CLAUDE_MCP="$(serena_mcp_claude_state "$root")"
    SERENA_GENERATED_STALE="$(serena_generated_stale_state "$root")"
    if [[ -f "$root/.agently/generated/serena/claude-code.commands.sh" ]]; then
      if [[ -x "$root/.agently/generated/serena/claude-code.commands.sh" ]]; then
        SERENA_GENERATED_SCRIPT_EXEC="yes"
      else
        SERENA_GENERATED_SCRIPT_EXEC="no"
      fi
    fi
  fi

  if [[ "$SERENA_ENABLED" == "true" && "$SERENA_PACK_PRESENT" != "yes" ]]; then
    SERENA_WARNINGS+=("serena.enabled=true but the Serena pack is absent.")
  fi
  if [[ "$SERENA_ENABLED" != "true" && "$SERENA_PACK_PRESENT" == "yes" ]]; then
    SERENA_INFO+=("Serena pack is present but serena.enabled=false.")
  fi
  if [[ "$SERENA_ENABLED" != "true" && ( "$SERENA_CODEX_MCP" == "configured" || "$SERENA_CLAUDE_MCP" == "configured" ) ]]; then
    SERENA_WARNINGS+=("MCP is configured while serena.enabled=false.")
  fi
  if [[ "$SERENA_PROFILE" == "edit" ]]; then
    SERENA_WARNINGS+=("Mutation-capable Serena profile is active.")
    if [[ "$SERENA_CODEX_MCP" != "configured" && "$SERENA_CLAUDE_MCP" != "configured" ]]; then
      SERENA_INFO+=("serena.profile=edit but no Serena MCP client appears configured.")
    fi
  fi
  if [[ "$SERENA_PROJECT_YML" == "found" && "$SERENA_ENABLED" != "true" ]]; then
    SERENA_INFO+=(".serena/project.yml exists while serena.enabled=false.")
  fi
  if [[ "$SERENA_CODEX_MCP" == "duplicate" ]]; then
    SERENA_WARNINGS+=("Duplicate Codex Serena MCP blocks detected.")
  fi
  if [[ "$SERENA_GENERATED_STALE" == "yes" ]]; then
    SERENA_INFO+=("Generated Serena files may be from a different Agently version.")
  fi
  if [[ "$SERENA_GENERATED_SCRIPT_EXEC" == "no" ]]; then
    SERENA_WARNINGS+=("Generated Claude Code Serena command script is not executable.")
  fi
}

serena_state_json() {
  printf '{'
  printf '"enabled":'; json_bool "$SERENA_ENABLED"; printf ','
  printf '"profile":'; json_string "$SERENA_PROFILE"; printf ','
  printf '"profile_valid":'; json_bool "$SERENA_PROFILE_VALID"; printf ','
  printf '"pack_present":'; json_bool "$SERENA_PACK_PRESENT"; printf ','
  printf '"command_status":'; json_string "$SERENA_CMD_STATUS"; printf ','
  printf '"command":'; json_string "$SERENA_CMD"; printf ','
  printf '"version":'; json_string "$SERENA_VERSION"; printf ','
  printf '"tokens_verified":'; json_bool "$SERENA_TOKENS_VERIFIED"; printf ','
  printf '"project_yml":'; json_string "$SERENA_PROJECT_YML"; printf ','
  printf '"cache":'; json_string "$SERENA_CACHE"; printf ','
  printf '"memories":'; json_string "$SERENA_MEMORIES"; printf ','
  printf '"memory_count":%s,' "$SERENA_MEMORY_COUNT"
  printf '"memories_reviewed":'; json_bool "$SERENA_MEMORIES_REVIEWED"; printf ','
  printf '"codex_mcp":'; json_string "$SERENA_CODEX_MCP"; printf ','
  printf '"claude_code_mcp":'; json_string "$SERENA_CLAUDE_MCP"; printf ','
  printf '"generated_stale":'; json_bool "$SERENA_GENERATED_STALE"; printf ','
  printf '"warnings":'; json_string_array "${SERENA_WARNINGS[@]}"; printf ','
  printf '"info":'; json_string_array "${SERENA_INFO[@]}"
  printf '}'
}

serena_status_markdown() {
  cat <<EOF
# Agently Serena Status

## State

- Enabled: $SERENA_ENABLED
- Profile: $SERENA_PROFILE
- Profile valid: $SERENA_PROFILE_VALID
- Pack present: $SERENA_PACK_PRESENT
- Serena command: $SERENA_CMD_STATUS
- Serena executable: ${SERENA_CMD:-none}
- Serena version: $SERENA_VERSION
- Launch tokens verified locally: $SERENA_TOKENS_VERIFIED
- Repo root: ${SERENA_ROOT:-none}
- .serena/project.yml: $SERENA_PROJECT_YML
- .serena/cache: $SERENA_CACHE
- .serena/memories: $SERENA_MEMORIES
- Memory count: $SERENA_MEMORY_COUNT
- Memories reviewed: $SERENA_MEMORIES_REVIEWED
- Codex MCP: $SERENA_CODEX_MCP
- Claude Code MCP: $SERENA_CLAUDE_MCP
- Generated files stale: $SERENA_GENERATED_STALE
- Generated Claude Code script executable: $SERENA_GENERATED_SCRIPT_EXEC

## Warnings

EOF
  if [[ "${#SERENA_WARNINGS[@]}" -eq 0 ]]; then
    printf -- '- None.\n'
  else
    printf -- '- %s\n' "${SERENA_WARNINGS[@]}"
  fi
  cat <<'EOF'

## Info

EOF
  if [[ "${#SERENA_INFO[@]}" -eq 0 ]]; then
    printf -- '- None.\n'
  else
    printf -- '- %s\n' "${SERENA_INFO[@]}"
  fi
  cat <<'EOF'

## Next Steps

```bash
agently mcp status
agently mcp add serena --client codex
agently serena onboard --client codex
agently serena memories check
```
EOF
}

serena_doctor_report() {
  local root="$1"
  serena_collect_state "$root"
  cat <<'EOF'

## Serena

EOF
  serena_status_markdown | sed '1d'
}

cmd_serena() {
  local sub="${1:-help}"
  if [[ $# -gt 0 ]]; then
    shift
  fi
  case "$sub" in
    status) serena_status "$@" ;;
    create-project) serena_create_project "$@" ;;
    onboard) serena_onboard "$@" ;;
    memories) serena_memories "$@" ;;
    profile) serena_profile_cmd "$@" ;;
    smoke) serena_smoke "$@" ;;
    code-intel)
      cat <<'EOF'
# Serena Code Intelligence

Future work: Agently will not drive an agent/MCP semantic inspection session.
Implement this only when Serena exposes a deterministic non-LLM CLI path for the needed semantic data.
EOF
      ;;
    workflow-report)
      cat <<'EOF'
# Serena Workflow Report

Future work: workflow reports are deferred unless they remain deterministic wrappers over local Agently and filesystem state.
EOF
      ;;
    help|-h|--help|"") serena_usage ;;
    *) die "unknown serena command: $sub" ;;
  esac
}

serena_status() {
  local json=0 root
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --json) json=1; shift ;;
      -h|--help) serena_usage; return 0 ;;
      *) die "unknown serena status option: $1" ;;
    esac
  done
  root="$(require_initialized)"
  serena_collect_state "$root"
  if [[ "$json" -eq 1 ]]; then
    serena_state_json
    printf '\n'
  else
    serena_status_markdown
  fi
}

cmd_mcp() {
  local sub="${1:-help}"
  if [[ $# -gt 0 ]]; then
    shift
  fi
  case "$sub" in
    status) mcp_status "$@" ;;
    add) mcp_add "$@" ;;
    remove) mcp_remove "$@" ;;
    help|-h|--help|"") mcp_usage ;;
    *) die "unknown mcp command: $sub" ;;
  esac
}

mcp_status() {
  local json=0 root
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --json) json=1; shift ;;
      -h|--help) mcp_usage; return 0 ;;
      *) die "unknown mcp status option: $1" ;;
    esac
  done
  root="$(repo_root)"
  SERENA_CODEX_MCP="$(serena_mcp_codex_state)"
  SERENA_CLAUDE_MCP="$(serena_mcp_claude_state "$root")"
  if [[ "$json" -eq 1 ]]; then
    printf '{"codex":'; json_string "$SERENA_CODEX_MCP"; printf ',"claude_code":'; json_string "$SERENA_CLAUDE_MCP"; printf '}\n'
  else
    cat <<EOF
# Agently MCP Status

- Codex MCP: $SERENA_CODEX_MCP
- Claude Code MCP: $SERENA_CLAUDE_MCP
EOF
  fi
}

mcp_parse_common() {
  MCP_CLIENT=""
  MCP_PROFILE=""
  MCP_APPLY=0
  MCP_SCOPE="project"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --client)
        [[ $# -ge 2 ]] || die "--client requires a value"
        MCP_CLIENT="$2"; serena_client_valid "$MCP_CLIENT" || die "invalid client: $MCP_CLIENT"
        shift 2 ;;
      --profile)
        [[ $# -ge 2 ]] || die "--profile requires a value"
        MCP_PROFILE="$(serena_profile_normalize "$2")" || die "invalid Serena profile: $2"
        shift 2 ;;
      --apply) MCP_APPLY=1; shift ;;
      --scope)
        [[ $# -ge 2 ]] || die "--scope requires a value"
        case "$2" in project|user) MCP_SCOPE="$2" ;; *) die "--scope must be project or user" ;; esac
        shift 2 ;;
      -h|--help) mcp_usage; return 2 ;;
      *) die "unknown mcp option: $1" ;;
    esac
  done
  [[ -n "$MCP_CLIENT" ]] || die "--client is required"
  if [[ -z "$MCP_PROFILE" ]]; then
    MCP_PROFILE="$(profile_get_value serena.profile)"
    MCP_PROFILE="$(serena_profile_normalize "$MCP_PROFILE")" || MCP_PROFILE="lite"
  fi
}

mcp_add() {
  [[ "${1:-}" == "serena" ]] || die "usage: agently mcp add serena --client <codex|claude-code>"
  shift
  local root project
  root="$(require_initialized)"
  project="$(basename "$root")"
  mcp_parse_common "$@"
  case "$MCP_CLIENT" in
    codex) mcp_add_codex "$root" "$project" "$MCP_PROFILE" "$MCP_APPLY" ;;
    claude-code) mcp_add_claude "$root" "$project" "$MCP_PROFILE" "$MCP_APPLY" "$MCP_SCOPE" ;;
  esac
}

mcp_remove() {
  [[ "${1:-}" == "serena" ]] || die "usage: agently mcp remove serena --client <codex|claude-code>"
  shift
  local root
  root="$(repo_root)"
  mcp_parse_common "$@"
  case "$MCP_CLIENT" in
    codex) mcp_remove_codex "$root" "$MCP_APPLY" ;;
    claude-code) mcp_remove_claude "$MCP_APPLY" "$MCP_SCOPE" ;;
  esac
}

mcp_add_codex() {
  local root="$1" project="$2" profile="$3" apply="$4" file backup ts snippet src
  src="$(serena_templates_dir)/generated/serena/codex.config.toml.example.tmpl"
  serena_render_generated_file "$src" "$root/.agently/generated/serena/codex.config.toml.example" \
    0644 "$project" "$root" "$profile" "codex" "agently mcp add serena --client codex" 0
  snippet="$root/.agently/generated/serena/codex.config.toml.example"
  if [[ "$apply" -eq 0 ]]; then
    cat <<EOF
# Serena Codex MCP Snippet Prepared

- Snippet: \`$snippet\`
- User config target: \`$(serena_codex_config_path)\`

Review the snippet, then apply manually or run:

\`\`\`bash
agently mcp add serena --client codex --apply
\`\`\`
EOF
    return 0
  fi
  file="$(serena_codex_config_path)"
  if [[ "$(serena_codex_mcp_block_count "$file")" -gt 0 ]]; then
    die "Codex Serena MCP block already exists in $file. Refusing to replace it; edit manually."
  fi
  mkdir -p "$(dirname "$file")"
  ts="$(date -u '+%Y%m%dT%H%M%SZ')"
  backup="$file.agently-backup-$ts"
  if [[ -f "$file" ]]; then
    cp "$file" "$backup"
  else
    : > "$backup"
    : > "$file"
  fi
  {
    printf '\n'
    cat "$snippet"
    printf '\n'
  } >> "$file"
  cat <<EOF
# Serena Codex MCP Applied

- Config: \`$file\`
- Backup: \`$backup\`

Rollback:

\`\`\`bash
cp "$backup" "$file"
\`\`\`
EOF
  if has_cmd diff; then
    printf '\n## Diff\n\n```diff\n'
    diff -u "$backup" "$file" || true
    printf '```\n'
  fi
}

mcp_remove_codex() {
  local apply="$2" file backup ts tmp
  file="$(serena_codex_config_path)"
  if [[ "$apply" -eq 0 ]]; then
    cat <<EOF
# Serena Codex MCP Removal

Review \`$file\` and remove the Agently-generated Serena block manually, or run:

\`\`\`bash
agently mcp remove serena --client codex --apply
\`\`\`
EOF
    return 0
  fi
  [[ -f "$file" ]] || die "Codex config not found: $file"
  grep -Fq 'GENERATED/REVIEWABLE snippet from Agently' "$file" || die "Serena block is not clearly Agently-generated; remove manually from $file"
  ts="$(date -u '+%Y%m%dT%H%M%SZ')"
  backup="$file.agently-backup-$ts"
  tmp="$(mktemp "$(dirname "$file")/.config.toml.tmp.XXXXXX")"
  cp "$file" "$backup"
  awk '
    /GENERATED\/REVIEWABLE snippet from Agently/ { skipping = 1; next }
    skipping && /^\[mcp_servers\.serena\][[:space:]]*$/ { next }
    skipping && /^\[/ { skipping = 0 }
    !skipping { print }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
  cat <<EOF
# Serena Codex MCP Removed

- Config: \`$file\`
- Backup: \`$backup\`

Rollback:

\`\`\`bash
cp "$backup" "$file"
\`\`\`
EOF
}

mcp_add_claude() {
  local root="$1" project="$2" profile="$3" apply="$4" scope="$5" serena_cmd src
  src="$(serena_templates_dir)/generated/serena/claude-code.commands.sh.tmpl"
  serena_render_generated_file "$src" "$root/.agently/generated/serena/claude-code.commands.sh" \
    0755 "$project" "$root" "$profile" "claude-code" "agently mcp add serena --client claude-code" 0
  if [[ "$apply" -eq 0 ]]; then
    cat <<EOF
# Serena Claude Code MCP Commands Prepared

- Script: \`$root/.agently/generated/serena/claude-code.commands.sh\`

Review the script, then run it manually or apply through Agently:

\`\`\`bash
agently mcp add serena --client claude-code --apply
\`\`\`
EOF
    return 0
  fi
  has_cmd claude || die "Claude Code CLI not found; cannot apply Claude MCP config"
  serena_cmd="$(serena_command_for_snippet)"
  if [[ "$scope" == "user" ]]; then
    claude mcp add --scope user serena -- "$serena_cmd" start-mcp-server --context claude-code --project-from-cwd
  else
    claude mcp add serena -- "$serena_cmd" start-mcp-server --context claude-code --project "$root"
  fi
}

mcp_remove_claude() {
  local apply="$1" scope="$2"
  if [[ "$apply" -eq 0 ]]; then
    cat <<'EOF'
# Serena Claude Code MCP Removal

Remove through Claude Code:

```bash
claude mcp remove serena
```
EOF
    return 0
  fi
  has_cmd claude || die "Claude Code CLI not found; cannot remove Claude MCP config"
  if [[ "$scope" == "user" ]]; then
    claude mcp remove --scope user serena
  else
    claude mcp remove serena
  fi
}

serena_create_project() {
  local apply=0 index=0 root project profile src dst content cmd backup ts tmp exit_code
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --apply) apply=1; shift ;;
      --index) index=1; shift ;;
      -h|--help) serena_usage; return 0 ;;
      *) die "unknown create-project option: $1" ;;
    esac
  done
  root="$(require_initialized)"
  project="$(basename "$root")"
  profile="$(profile_get_value serena.profile)"
  profile="$(serena_profile_normalize "$profile")" || profile="lite"
  src="$(serena_templates_dir)/generated/serena/project.yml.example.tmpl"
  dst="$root/.agently/generated/serena/project.yml.example"
  serena_render_generated_file "$src" "$dst" 0644 "$project" "$root" "$profile" "codex" "agently serena create-project" 0
  if [[ "$apply" -eq 0 ]]; then
    cat <<EOF
# Serena Project Example Prepared

- Example: \`$dst\`

Agently does not own Serena project schema.
Review the example or prefer Serena's own generator, then apply explicitly:

\`\`\`bash
agently serena create-project --apply
\`\`\`
EOF
    return 0
  fi
  mkdir -p "$root/.serena"
  if [[ -f "$root/.serena/project.yml" ]]; then
    ts="$(date -u '+%Y%m%dT%H%M%SZ')"
    backup="$root/.serena/project.yml.agently-backup-$ts"
    cp "$root/.serena/project.yml" "$backup"
    note "backed up existing .serena/project.yml to $backup"
  fi
  if cmd="$(serena_resolve_cmd 2>/dev/null)"; then
    tmp="$(mktemp "$root/.serena/project.yml.tmp.XXXXXX")"
    set +e
    "$cmd" project generate-yml > "$tmp" 2>/dev/null
    exit_code=$?
    set -e
    if [[ "$exit_code" -eq 0 && -s "$tmp" ]]; then
      mv "$tmp" "$root/.serena/project.yml"
    else
      rm -f "$tmp"
      cp "$dst" "$root/.serena/project.yml"
    fi
  else
    cp "$dst" "$root/.serena/project.yml"
  fi
  cat <<EOF
# Serena Project File Written

- File: \`$root/.serena/project.yml\`

This file is Serena-owned operational state.
EOF
  if [[ "$index" -eq 1 ]]; then
    if cmd="$(serena_resolve_cmd 2>/dev/null)"; then
      "$cmd" project index || warn "Serena project index command failed"
    else
      warn "Serena command not found; skipped explicit indexing"
    fi
  fi
}

serena_onboard() {
  local client="" dry_run=0 profile="" output="" root project prompt default_prompt count snapshot report
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --client)
        [[ $# -ge 2 ]] || die "--client requires a value"
        client="$2"; serena_client_valid "$client" || die "invalid client: $client"
        shift 2 ;;
      --dry-run) dry_run=1; shift ;;
      --profile)
        [[ $# -ge 2 ]] || die "--profile requires a value"
        profile="$(serena_profile_normalize "$2")" || die "invalid Serena profile: $2"
        shift 2 ;;
      --output)
        [[ $# -ge 2 ]] || die "--output requires a value"
        output="$2"; shift 2 ;;
      -h|--help) serena_usage; return 0 ;;
      *) die "unknown onboard option: $1" ;;
    esac
  done
  [[ -n "$client" ]] || die "--client is required"
  root="$(require_initialized)"
  project="$(basename "$root")"
  [[ -n "$profile" ]] || profile="$(profile_get_value serena.profile)"
  profile="$(serena_profile_normalize "$profile")" || profile="lite"
  default_prompt="$root/.agently/generated/serena/onboard.$client.md"
  prompt="$(serena_templates_dir)/generated/serena/onboard.$client.md.tmpl"
  serena_render_generated_file "$prompt" "$default_prompt" 0644 "$project" "$root" "$profile" "$client" "agently serena onboard --client $client" 0
  if [[ -n "$output" ]]; then
    serena_reject_serena_output_path "$root" "$output"
    mkdir -p "$(dirname "$output")"
    cp "$default_prompt" "$output"
  fi
  count="$(serena_memory_count "$root")"
  if [[ "$dry_run" -eq 0 ]]; then
    snapshot="$(serena_write_memory_snapshot "$root")"
    report="$root/.agently/reports/serena-onboarding-summary.md"
    mkdir -p "$(dirname "$report")"
    cat > "$report" <<EOF
# Serena Onboarding Summary

- generated: $(now)
- client: $client
- profile: $profile
- prompt: .agently/generated/serena/onboard.$client.md
- memory_count_before: $count
- memory_snapshot: $(rel_to_root "$root" "$snapshot")

Prepared Serena onboarding prompt.
Agently did not run onboarding.
Agently did not create memories.
Agently did not mutate source.
EOF
  fi
  cat <<EOF
# Serena Onboarding Prepared

- Client: $client
- Profile: $profile
- Prompt: \`$default_prompt\`
- Memory count before: $count

Prepared Serena onboarding prompt.
Agently did not run onboarding.
Agently did not create memories.
Agently did not mutate source.

Run the generated prompt inside Codex or Claude Code, then run:

\`\`\`bash
agently serena memories check
\`\`\`
EOF
}

serena_memories() {
  local sub="${1:-help}"
  if [[ $# -gt 0 ]]; then
    shift
  fi
  case "$sub" in
    list) serena_memories_list "$@" ;;
    check) serena_memories_check "$@" ;;
    help|-h|--help|"") serena_usage ;;
    *) die "unknown serena memories command: $sub" ;;
  esac
}

serena_memories_list() {
  [[ $# -eq 0 ]] || die "serena memories list takes no arguments"
  local root dir file rel size mtime
  root="$(repo_root)"
  dir="$root/.serena/memories"
  if [[ ! -d "$dir" ]]; then
    printf '# Serena Memories\n\nNo memories found.\n'
    return 0
  fi
  printf '# Serena Memories\n\n'
  while IFS= read -r file; do
    rel="$(rel_to_root "$root" "$file")"
    size="$(wc -c < "$file" 2>/dev/null || printf '0')"
    mtime="$(date -u -r "$file" '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || printf 'unknown')"
    printf -- '- `%s` (%s bytes, %s)\n' "$rel" "$size" "$mtime"
  done < <(find "$dir" -type f | sort)
}

serena_memories_check() {
  local mark=0 root old current report created changed unchanged deleted line rel old_line
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mark-reviewed) mark=1; shift ;;
      -h|--help) serena_usage; return 0 ;;
      *) die "unknown memories check option: $1" ;;
    esac
  done
  root="$(require_initialized)"
  old="$(serena_memory_snapshot_file "$root")"
  current="$(mktemp)"
  serena_memory_snapshot_lines "$root" > "$current"
  report="$root/.agently/reports/serena-onboarding-summary.md"
  mkdir -p "$(dirname "$report")"
  created=""
  changed=""
  unchanged=""
  deleted=""
  if [[ -f "$old" ]]; then
    while IFS= read -r line; do
      [[ -n "$line" ]] || continue
      rel="${line%%|*}"
      old_line="$(grep -F -- "${rel}|" "$old" || true)"
      if [[ -z "$old_line" ]]; then
        created+="- $rel"$'\n'
      elif [[ "$old_line" == "$line" ]]; then
        unchanged+="- $rel"$'\n'
      else
        changed+="- $rel"$'\n'
      fi
    done < "$current"
    while IFS= read -r line; do
      [[ -n "$line" ]] || continue
      rel="${line%%|*}"
      if ! grep -Fq -- "${rel}|" "$current"; then
        deleted+="- $rel"$'\n'
      fi
    done < "$old"
  fi
  cat > "$report" <<EOF
# Serena Onboarding Summary

- generated: $(now)
- baseline: $([[ -f "$old" ]] && printf 'found' || printf 'missing')
- current_memory_count: $(serena_memory_count "$root")
- memories_reviewed: $([[ "$mark" -eq 1 ]] && printf 'true' || printf '%s' "$(serena_state_get "$root" memories_reviewed)")

## Created

${created:-_(none)_}

## Changed

${changed:-_(none)_}

## Unchanged

${unchanged:-_(none)_}

## Deleted

${deleted:-_(none)_}

## Reminder

Review \`.serena/memories/\` before relying on Serena memories.
EOF
  cp "$current" "$old"
  rm -f "$current"
  serena_state_set "$root" last_memory_snapshot_at "$(now)"
  serena_state_set "$root" last_memory_count "$(serena_memory_count "$root")"
  serena_state_set "$root" last_memory_snapshot_file ".agently/reports/serena-memories.snapshot"
  if [[ "$mark" -eq 1 ]]; then
    serena_state_set "$root" memories_reviewed true
  fi
  cat "$report"
}

serena_profile_cmd() {
  local sub="${1:-get}" profile
  case "$sub" in
    get)
      [[ $# -le 1 ]] || die "usage: agently serena profile [get]"
      require_initialized >/dev/null
      profile="$(profile_get_value serena.profile)"
      serena_profile_normalize "$profile" || printf '%s\n' "$profile"
      ;;
    set)
      [[ $# -eq 2 ]] || die "usage: agently serena profile set <lite|review|edit>"
      profile="$(serena_profile_normalize "$2")" || die "invalid Serena profile: $2"
      profile_set serena.profile "$profile"
      ;;
    -h|--help|help) serena_usage ;;
    *) die "unknown serena profile command: $sub" ;;
  esac
}

serena_smoke() {
  local output="" json=0 root before_git after_git before_mem after_mem fail=0 notes=() profile tmp
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output)
        [[ $# -ge 2 ]] || die "--output requires a value"
        output="$2"; shift 2 ;;
      --json) json=1; shift ;;
      -h|--help) serena_usage; return 0 ;;
      *) die "unknown smoke option: $1" ;;
    esac
  done
  root="$(require_initialized)"
  before_git="$(git_status_short_for "$root")"
  before_mem="$(serena_memory_snapshot_lines "$root")"
  [[ -d "$root/.agently/integrations/serena" ]] || { fail=1; notes+=("Serena pack missing."); }
  [[ -f "$root/.agently/generated/serena/codex.config.toml.example" ]] || { fail=1; notes+=("Codex snippet missing."); }
  [[ -x "$root/.agently/generated/serena/claude-code.commands.sh" ]] || { fail=1; notes+=("Claude Code command script missing or not executable."); }
  profile="$(profile_get_value serena.profile)"
  serena_profile_normalize "$profile" >/dev/null || { fail=1; notes+=("Invalid Serena profile: $profile"); }
  serena_resolve_cmd >/dev/null 2>&1 || notes+=("Serena executable absent; skipped version check.")
  tmp="$(mktemp)"
  serena_render_template "$(serena_templates_dir)/generated/serena/codex.config.toml.example.tmpl" "$(basename "$root")" "$root" "${profile:-lite}" codex "agently serena smoke" > "$tmp"
  grep -Fq -- '--context=codex' "$tmp" || { fail=1; notes+=("Codex context token missing."); }
  rm -f "$tmp"
  after_git="$(git_status_short_for "$root")"
  after_mem="$(serena_memory_snapshot_lines "$root")"
  [[ "$before_git" == "$after_git" ]] || { fail=1; notes+=("Git status changed during smoke."); }
  [[ "$before_mem" == "$after_mem" ]] || { fail=1; notes+=("Serena memories changed during smoke."); }
  if [[ "$json" -eq 1 ]]; then
    printf '{"ok":'; [[ "$fail" -eq 0 ]] && printf 'true' || printf 'false'
    printf ',"notes":'; json_string_array "${notes[@]}"; printf '}\n'
  else
    {
      printf '# Serena Smoke\n\n'
      printf -- '- Result: %s\n' "$([[ "$fail" -eq 0 ]] && printf ok || printf fail)"
      printf -- '- Repo: `%s`\n' "$root"
      printf -- '- Serena executable: %s\n' "$(serena_resolve_cmd 2>/dev/null || printf 'missing')"
      printf '\n## Notes\n\n'
      if [[ "${#notes[@]}" -eq 0 ]]; then
        printf -- '- None.\n'
      else
        printf -- '- %s\n' "${notes[@]}"
      fi
    } | {
      if [[ -n "$output" ]]; then
        serena_reject_serena_output_path "$root" "$output"
        mkdir -p "$(dirname "$output")"
        cat > "$output"
        note "wrote Serena smoke report: $output"
      else
        cat
      fi
    }
  fi
  [[ "$fail" -eq 0 ]] || return 1
}
